version: "3"
services:
    test:
        build: ../
        environment:
            FLAG: "flag{a63b4d37-7681-4850-b6a7-0d7109febb19}"
        ports:
            - 8888:8888
        restart: unless-stopped
